#
# Module manifest for module 'PolicyRemediation'
#
# Generated by: Enterprise Cloud Services
#
# Generated on: 07/25/2023
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'PolicyRemediation.psm1'

    ModuleVersion = '1.0.0'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    GUID = 'b702865f-a42c-4585-8302-9022c36f4e25'

    Author = 'Enterprise Cloud Services'

    CompanyName = 'UPMC'

    Copyright = '(c) Enterprise Cloud Services. All rights reserved.'

    Description = 'This module contains functions to write to an Azure SQL database for policy remediation automation events.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '7.0'

    FunctionsToExport = @('Write-ToDeploymentHistory', 'Write-ToDatabase')

    CmdletsToExport = @()

    VariablesToExport = @()

    AliasesToExport = @()

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
}